config/routes.rb
Koding::Application.routes.draw do
  resources :units

  devise_for :users do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :tracks
  
  root to: "tracks#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :track
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :track
  has_many :units
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :unit
end

app/models/track.rb
class Track < ActiveRecord::Base
	has_many :units
  belongs_to :user
  has_many :categories
  has_many :levels
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :track
  has_many :tags
  belongs_to :level
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_track, only: [:show, :edit, :update, :destroy]


  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
    @users = User.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @unit = Unit.new
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)
    @track.user = current_user

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render action: 'show', status: :created, location: @track }
      else
        format.html { render action: 'new' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
    level = Level.new
    level.track = @track
    level.level = 0
    level.save
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    redirect_to "/tracks/#{@unit.track_id}"
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    @track = @unit.track
    if @track.levels.last.units.count == 3
      level = Level.new
      level.level = @track.levels.last.level + 1
      level.track_id = @track.id
      level.save
    end
    @unit.level_id = @track.levels.last.id 

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:track_id, :level_id, :category, :level, :title, :content, :votes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0", :name => "viewport"}/
    %title Koding
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    %link{:href => "semantic.min.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "semantic.min.js"}
    = csrf_meta_tags

  %body
    .ui.piled.masthead.segment
      .ui.page.grid
        .column
          .ui.hidden.transition.information
            %h1.ui.header
              = yield(:banner) 
            .large.basic.animated.ui.button
              - if user_signed_in?
                .visible.content LOGOUT
                = link_to "See you :)", destroy_user_session_path, :method => :delete, class: "hidden content"
              - else
                .visible.content Make my everytrack
                %a.hidden.content{href: "/users/sign_in"} Check-me-in!
            %a.large.basic.animated.ui.button{href: "/tracks"}
              .visible.content Track listings
              .hidden.content Gotta track-em' all!
            %a.large.basic.animated.ui.button{href: "/tracks/new"}
              .visible.content Feeling crafty?
              .hidden.content Make new track!

    = yield

app/views/tracks/_form.html.haml
= form_for(@track) do |f|
  - if @track.errors.any?
    #error_explanation
      %h2
        = pluralize(@track.errors.count, "error")
        prohibited this track from being saved:
      %ul
        - @track.errors.full_messages.each do |msg|
          %li= msg

  .ui.massive.input.fluid.right.aligned.segment
    = f.text_field :title, autofocus: true, placeholder: "programming, cooking, gaming, whatever.."
  = f.submit "YUP", {class: "ui right green basic button"}

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.haml
- content_for :banner, "Awesome tracks people are making"
.ui.stackable.grid
  - if @tracks.empty?

    .ui.stackable.grid
      .six.wide.column
      .four.wide.column
        .ui.card
          .image.dimmable
            %img{:src => "/images/steve.jpg"}/
        %a.large.ui.button{href: "/tracks/new"} Get famous, make the first track!

  - else
    - @tracks.each do |track|
      .two.wide.column
      .four.wide.column
        .ui.stacked.segment
          %h4.ui.header= link_to track.title, File.join("/tracks/#{track.id}")
          %p Crafted by #{track.user.email}, with #{track.levels.count} levels.
      .two.wide.column

app/views/tracks/new.html.haml
- content_for :banner, "Let's make awesome tracks!"

.ui.stackable.grid
  .six.wide.column
  .four.wide.column
    .ui.card
      .image.dimmable
        %img{:src => "/images/steve.jpg"}/
    .large.ui.button.track Create your track

    %p With a track, you can guide your readers through the path you took to learning a new skill.
    %p Creating your track is super easy, leaving you to work on what you're best at - teaching.


  .six.wide.column

.ui.modal.track
  %i.close.icon
  .header
    What's this track about?
  .content
    = render 'form'

app/views/tracks/show.html.haml
- markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
- if user_signed_in? and @track.user == current_user
  - content_for :banner, "You recommend picking up #{@track.title} this way."
- else
  - content_for :banner, "#{@track.user.email} recommends picking up #{@track.title} this way."

- if @track.units.count == 0
  
  .ui.stackable.grid
    .six.wide.column
    .four.wide.column
      .ui.card
        .image.dimmable
          %img{:src => "/images/steve.jpg"}/
      -if user_signed_in? and current_user == @track.user
        .large.ui.button.unit Add first unit!
        %p Tracks are composed of units, that convey information, one step at a time.
        %p So.. if a reader wants to pick up #{@track.title}, what's the best place to start?


      - else

        %h4.ui.header You gotta wait!
        %p While #{@track.user.email} recommends some units for you to read up, why not grab some coffee?

- else
  .ui.stackable.grid
    .two.wide.column
    .twelve.wide.column
      -if user_signed_in? and current_user == @track.user
        .large.ui.button.unit Add another unit

      - @track.levels.each do |level|
        %h3.ui.horizontal.header.divider
          %a{:href => "#level#{level.level}", :name => "level#{level.level}"}
            %i.level.down.icon
            = "Level #{level.level}"

        -#
          .ui.segment
            %h4.ui.header So you want to build things
            %p Hackers primarily build things. That's what makes them happy.
            %p There's a common misconception, that leads people into believing hackers are the equivalent of criminal troublemakers.. you know, breaking into your Facebook account and everything.

        .ui.stackable.three.column.grid
          - level.units.each do |unit|
            -#
              .column
                  .large.ui.button.unit Add another unit
            .column
              .ui.card
                .image.dimmable
                  %img{:src => "/images/wireframe/image.png"}/
                .content
                  .header
                    = unit.title
                  .meta
                    %a.group> #{unit.category}
                    -#
                      ,
                      %a.group essays
                  .description
                    = raw markdown.render unit.content

                .extra.content
                  %a.right.floated.created{href: "http://twitter.com/SarupBanskota"} Argue over Twitter
                  = unit.votes
                  .ui.heart.rating{"data-max-rating" => "1", "data-rating" => "0"}
                    %i.icon
                -#
                  %a.friends Upvote
      %br/
      -if user_signed_in? and current_user == @track.user
        .large.ui.button.unit Add another unit

    .ui.masthead.segment
      .ui.page.grid
        .column
          .ui.hidden.transition.information
            %p
              %i.india.flag>
              Hello from T432.
            %br/
            %br/
            %br/

.ui.modal.track
  %i.close.icon
  .header
    What's this track about?
  .content
    = render 'form'

.ui.modal.new.unit
  %i.close.icon
  .header
    What's this unit about?
  .content
    = render 'units/form'

app/views/units/_form.html.haml
= form_for(@unit) do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2
        = pluralize(@unit.errors.count, "error")
        prohibited this unit from being saved:
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg

  .ui.massive.input.fluid.segment
    %h3 Title
    = f.text_field :title, autofocus: true, placeholder: "understanding databases, learning to communicate, organizing the party"
    %h3 Content
    = f.text_field :content, placeholder: "roses are red, you are blue, oh baby, you give me the flu"
    %h3 Categories
    = f.text_field :category, placeholder: "DIY"
    = f.hidden_field :track_id, value: @track.id
  = f.submit "ADD", {class: "ui right green basic button"}

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <thead>
    <tr>
      <th>Track</th>
      <th>Category</th>
      <th>Level</th>
      <th>Title</th>
      <th>String,</th>
      <th>Content</th>
      <th>Text,</th>
      <th>Votes</th>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.track %></td>
        <td><%= unit.category %></td>
        <td><%= unit.level %></td>
        <td><%= unit.title %></td>
        <td><%= unit.string, %></td>
        <td><%= unit.content %></td>
        <td><%= unit.text, %></td>
        <td><%= unit.votes %></td>
        <td><%= unit.number %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Title:</strong>
  <%= @unit.title %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>